### ISSUE TITLE
How to resize iframe?

### ISSUE THREAD

**Issue by cayers71** [eouia/MMM-News#1]
Newb question - how do I shrink the size of the window?  Is the size defined by the .html template, or some variable within the MMM-News.js config file?

**Comment by eouia** [comment]
You can overwrite CSS. See the details of `MMM-News.css`. 
Add this into your `css/custom.css`.
```
#NEWS_DETAIL {
  top:10%;
  left:10%;
  width:80%;
  height:80%;
}
```
It will show 80% size instead original 100% size.

**Comment by cayers71** [comment]
Thanks, that works well for the popup window after selecting an article.  I may not have described what I want to modify correctly - how do I adjust the size of the on-screen window itself - the default view?  I have figured out how to modify the text size, but that does not trigger a window resize.

**Comment by eouia** [comment]
Hmmm I cannot understand your request. If you could, taking a picture or screenshot will be help to guess.

**Comment by swvalenti194** [comment]
I think I would like the same request.  The default size of the news feed module on the bottom bar is quite big.  Any way to make the size smaller so I can fit other modules without overlapping?  That make sense?

**Comment by eouia** [comment]
Add this into your ‘css/custom.css’
```
#NEWS.horizontal {
  font-size: 20px; // adjust for your wish
}
```

**Comment by eouia** [comment]
I'll close this issue since no more feedback. Have a nice day.

**Comment by harrykendal** [comment]
I’m having the same issue here I think. I would like to resize the entire module but adding 
#NEWS.horizontal {
  font-size: 20px; // adjust for your wish
}

Into my CSS file doesn’t seem to change anything?

**Comment by eouia** [comment]
@harrykendal 
Which file did you modify? `css/custom.css` would be. 
If you need more detail adjustments, See `MMM-News.css` and find proper selectors which you want to adjust, then rewrite it in your `css/custom.css`.

**Comment by harrykendal** [comment]
I’d like to modify the text of the headline and the brief description of the article.
I’m editing the css/custom as far as I’m aware but It’s not working?
Where do I input the changes in css/custom.css? E.g.

Body {

}

Do I put them within the “{ }”, or after ?

**Comment by eouia** [comment]
The default of `css/custom.css` makes ppl confused.
ignore `body { }`. (Or erase it). Put your code out of `body {}`.

**Comment by harrykendal** [comment]
Sorted it, I ended up editing the css of the news module with a little help off a friend who's good with CSS, thanks for your help & speedy responses anyway @eouia! Keep up the great work!
