### ISSUE TITLE
Running multiple instances of MMM-News

### ISSUE THREAD

**Issue by ThaoDChan** [eouia/MMM-News#2]
Is it possible to run multiple instances of MMM-News?
I´m using the horizontal view and would like to display multiple News articles from different sources stacked on top another.
What I´ve tried so far: 
- configured multiple instances in config.js (in different zones)
- tried messing with the .htm file
- tried messing with MMM-News.js and MMM-News.css

Sadly I was not able to run more than 1 window.
Help would be very much appreciated!

**Comment by eouia** [comment]
Sorry. It’s not supported.
