### ISSUE TITLE
monochrome filter

### ISSUE THREAD

**Issue by StuartIanNaylor** [eouia/MMM-News#3]
eouia is it possible to run the images through a monochrome filter like mmm-movies?
That for me would be cool and also have an old style 'newspaper' look.

**Comment by eouia** [comment]
Add this into your `css/custom.css`
```
#NEWS .articleImage {
    filter: grayscale(100%);
}
```
You can use other filters. See https://www.w3schools.com/cssref/css3_pr_filter.asp

**Comment by StuartIanNaylor** [comment]
You are just amazing !!! Many thanks.

**Comment by eouia** [comment]
I'll close this issue. Have a nice day.
