### ISSUE TITLE
dom.distiller

### ISSUE THREAD

**Issue by StuartIanNaylor** [eouia/MMM-News#4]
Not an issue just wondering if the iframe can be opened by dom.distiller?
Would be great to have those iframes in 'reader' mode.

**Comment by eouia** [comment]
I didn't tried it. I'm not sure it is availabe on Electron. I need more researches, but I have no idea at this moment.

**Comment by eouia** [comment]
Added.

**Comment by StuartIanNaylor** [comment]
Brilliant
