### ISSUE TITLE
News article flashes up twice, once in white, then in red.

### ISSUE THREAD

**Issue by harrykendal** [eouia/MMM-News#5]
With this module set up, I’m noticing the articles tend to flash up twice. The first time in white writing, then upon the second time it’s red, then it’ll show the next headline?
Has anybody got any ideas?

**Comment by eouia** [comment]
Weird. Can i see your configuration?

**Comment by harrykendal** [comment]
I will post config as soon as I can, out of town at the moment but will forward ASAP

**Comment by naufalwaffl** [comment]
yes I have the exact same issue! headlines appear twice, once in white then in red and after that it goes to the next news headlines...
what should be changed?

**Comment by naufalwaffl** [comment]
![20190315_120502](https://user-images.githubusercontent.com/46013460/54413161-d6348a00-471a-11e9-8ed3-22707ef726fa.jpg)

**Comment by eouia** [comment]
@naufalwaffl 
You've set your sources being duplicated.
```js
query: [
  {
    sources: "the-times-of-india, the-hindu",
  },
  {
    country: "in",
    className "redTitle"
  },
  {
    country: "in",
    category: "general",
    q: ""
  }
],
```
First source means articles from "the-times-of-india" and "the-hindu"
Second source means articles from All Indian media sources(which would have country code "in") with "redTitle" class (I guess this class name make title red)
Third source means also articles from All Indian media sources, but categorized with "general" and no searching keyword(q:"")

I think these 3 sources could have duplicated articles. By example, some articles of "the-hindu" might be gathered 3 times.

Adjust your sources to your purpose.

**Comment by naufalwaffl** [comment]
oh, I kind of guessed that... can I remove the below two sources and stick with the 1st one only?

**Comment by naufalwaffl** [comment]
yes I gave it a try and it works great, thanks friend!

**Comment by naufalwaffl** [comment]
> With this module set up, I’m noticing the articles tend to flash up twice. The first time in white writing, then upon the second time it’s red, then it’ll show the next headline?
> Has anybody got any ideas?

I hope this solves Harry's problem too :)

**Comment by harrykendal** [comment]
Will give this ago tonight if I’ve got the time, sounds logical to me, will you keep posted! Thanks

**Comment by harrykendal** [comment]
Perfect!!
My config now looks like 

query: [
  {
    sources: "bbc-news",
  },
  {
    country: "gb",
    category: "general",
    q: ""
  }
],
touchable: false,
items: 20




Thanks a lot buddy!

**Comment by eouia** [comment]
Nice to hear it. I'll close this issue. Have a nice day.

**Comment by eouia** [comment]
But some of your "bbc-news" could be duplicated. :D
