### ISSUE TITLE
Remove arrows on the news

### ISSUE THREAD

**Issue by eXGameStudio** [eouia/MMM-News#6]
Is there a way of removing/hide the green circles with white arrows on them ?

**Comment by eouia** [comment]
`touchable: false,`

**Comment by eXGameStudio** [comment]
nice!, worked like a charm. Is there a way of changing the title text color and to handle space between the image and the text below and avobe?.
Thanks a lot for writting me back this fast, you are awesome man!

**Comment by eouia** [comment]
See the MMM-News.css then override what you need on `css/custom.css`. Sorry this is DIY project, so there is no out-of-box silver bullets.
